### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rgusick** [AyrA/IsEmoji#1]
I'd like to leverage this library to return an emoji given the name. i.e.  GetEmojiFromName(string), where string is something like "grinning face" (or ":grinning face:"), "man genie", etc.

**Comment by AyrA** [comment]
I think that's beyond the scope of the library, because it's just intended to detect emoji. You can however get all emoji from it, and then feed them through a search function. Here's a very simple example:

```C#
Console.Write("Search string: ");
var search = Console.ReadLine();

var all = Emoji
    .GetAllGroups()
    .SelectMany(m => m.Subgroups.SelectMany(m => m.Emoji));
var found = all
    .Where(m => m.Name.Contains(search, StringComparison.InvariantCultureIgnoreCase))
    .OrderBy(m => m.Name.Length - search.Length)
    .ThenBy(m => m.Name)
    .ToList();

Console.WriteLine("Found {0} emoji", found.Count);
foreach (var item in found)
{
    Console.WriteLine("{0}\t{1}", item.Name, item.Emoji);
}
```

If you want to use a more complex search, I suggest looking for a purpose built string search library that has a better likeliness implementation instead of what I just did.

Tip: If your application is using a database engine (an SQL server) look into its fulltext index function. These may provide adequate search capabilities for your needs.

**Comment by rgusick** [comment]
Thanks for the reply. I may just roll my own based on the parsing of https://unicode.org/Public/emoji/latest/emoji-test.txt
